### ISSUE TITLE
usage question 1: setting methods (functions) in constructors

### ISSUE THREAD

**Issue by ibeatty** [jkuczm/MathematicaClasslessObjects#11]
Hi.

First: Thanks 10^3 for creating and sharing this. It is a Godsend.

Second: Please forgive me if this is the wrong venue for communicating questions to you. I don't have enough reputation points on Stack Exchange yet to post a comment on your excellent answer there, and I'm new to GitHub so I'm unfamiliar with the conventions.

Third: I'm trying to use this package in a _Mathematica_ project, and I'm having trouble figuring out how to accomplish a couple of less basic things. The first is simple to describe: Is it possible to define a "constructor" that takes methods (set-delayed rules) as well as properties (set-immediately rules)? I tried the obvious, simply passing a function in as one of the constructor parameters and then setting the object rule to it, but no luck:

``` Mathematica
ancestor@construct[obj_Symbol, v0$_, r0$_, f$_Function] := (
  DeclareObject[obj, $self];
  obj@r0 = r0$;
  obj@v0 = v0$;
  obj@f := f$;
  obj )
```

I've tried with `:=` and `=` in that code, and I've tried various methods of defining the function that I pass to the constructor: delayed or not, as a normal f[x_] rule or a pure function, etc.

``` Mathematical
ClearAll[child];
ff = (#^2) &;
ancestor@construct[child, 20, 0, ff];
```

In all cases, I'm getting the following error message:

```
Object::objectMember: The call child@0 didn't match any of defined member patterns in child nor in its ancestors: {ancestor,Object}.
```

I can, of course, bypass the constructor and simply define the method for the child directly, with setDelayed, but it would be helpful (and ultimately easier for users of my project) if I could handle it in the constructor. Is this possible? Am I being dumb or blind?

BTW, I'm moderately but not expertly skilled with Mathematica, but I'm not yet conversant with the subtleties of HoldAll and when/how to use it.

Thanks,
:Ian

**Comment by jkuczm** [comment]
In _Mathematica_ `child@f[a]` translates to `child[f[a]]`. Your constructor doesn't define any pattern that could match `child[f[a]]`. It defines only `child[f]` pattern.

So there are two possible solutions:
1. With your current constructor definition use `(child@f)[a]` or `child[f][a]` instead of `child@f[a]`.
2. Change `obj@f := f$;` to `obj@f[args___] := f$[args];`, in your constructor, then use `child@f[a]`.

**Comment by ibeatty** [comment]
I get it. I tried your second object, and it works as advertised. Thanks!

If you will tolerate a follow-up question: In the constructor, how can I declare such a method as "Listable"? I tried

``` Mathematica
ancestor@construct[obj_Symbol, a$_Function, v0$_: 0, r0$_: 0] := (
  DeclareObject[obj, $self];
  obj@a[args___] := a$[args];
  SetAttributes[obj@a, Listable];
  obj@r0 = r0$;
  obj@v0 = v0$;
  obj)
```

But when I try to invoke the constructor, I get an error: `SetAttributes::sym: "Argument child[a] at position 1 is expected to be a symbol. "`

The problem, of course, is obvious: SetAttributes expects a single symbol, rather than a composite object like `obj[a]`. The solution is not obvious, at least not to me. I can't figure out where to put a `SetAttributes[...]` call so that the argument would be a lone symbol, but would apply to the child function. It seems that in your OOP framework, methods will ALWAYS have a `something@name` format.

Suggestions?

Thanks,
:Ian

**Comment by jkuczm** [comment]
You could automatically add attributes to function that is called by `obj@a`.

First let's define function that adds attributes to pure functions:

``` Mathematica
ClearAll[addAttributes]
addAttributes[f_Function, attrs_] :=
    Replace[f, {
        HoldPattern@Function[body_] :> Function[Null, body, attrs],
        HoldPattern@Function[args_, body_] :> Function[args, body, attrs],
        HoldPattern@Function[args_, body_, currentAttrs_] :> 
            With[{allAttrs = DeleteDuplicates@Flatten@{currentAttrs, attrs}}, 
                Function[args, body, allAttrs]
            ]
   }]
```

Now use this function in your constructor:

``` Mathematica
ancestor@construct[obj_Symbol, a$_Function, v0$_: 0, r0$_: 0] := (
    DeclareObject[obj, $self];
    With[{listableA = addAttributes[a$, Listable]},
       obj@a[args___] := listableA[args]
    ];
    obj@r0 = r0$;
    obj@v0 = v0$;
    obj
)
```

It should work as expected:

``` Mathematica
ClearAll[child, f, x, y]
ancestor@construct[child, 5 + f[#] &];
child@a[x]
child@a[{{x}, y}]
(*
5 + f[x]
{{5 + f[x]}, 5 + f[y]}
*)
```

**Comment by jkuczm** [comment]
Be aware that above method will not work for `Hold...` attributes, since arguments will be evaluated when `child@a[...]` will be called. When arguments are passed to "internal function" it's too late to hold them.

**Comment by ibeatty** [comment]
It works!

I don't understand all that Deep Magic in the `addAttributes` function -- HoldPattern and :> and all that -- but perhaps someday I will. I'll puzzle over it.

Many thanks.

**Comment by ibeatty** [comment]
Instead of the `With[...]`, couldn't we just say

```
obj@a[args___] := addAttributes[a$, Listable][args];
```

? I tested that, and it seems to work equivalently.

**Comment by jkuczm** [comment]
Yes it works, but it evaluates `addAttributes` each time `child@a[...]` is called.

Version with `With` evaluates `addAttributes` only one time: when constructor is evaluated.

**Comment by ibeatty** [comment]
Aah. Gotcha.

**Comment by jkuczm** [comment]
Same as in your second issue, this should be easier and cleaner:

``` Mathematica
ancestor@a[l_List] := $self@a[#] & /@ l
ancestor@construct[obj_Symbol, a$_Function, v0$_: 0, r0$_: 0] := (
    DeclareObject[obj, $self];
    obj@a[t : Except[_List]] := a$[t];
    obj@r0 = r0$;
    obj@v0 = v0$;
    obj
)
```

**Comment by ibeatty** [comment]
Much nicer! I was hung up on using the `Listable` attribute, rather than simply making it work with lists.

Thanks again.
