### ISSUE TITLE
usage question 2: integrating a child object method once, not every time, to get a new function that can be called

### ISSUE THREAD

**Issue by ibeatty** [jkuczm/MathematicaClasslessObjects#12]
Hi again. Here's a second question. It is considerably more subtle and specialized, but perhaps you might find it interesting.

Each of the child objects I'm subclassing from a superclass object has a function we'll call `a[t_]`. The specific function differs for each child, but I've got superclass methods that use it (via your excellent `$self` syntax) to generate a set of graphs. Specifically, these superclass methods graph the function, its integral, and its second integral (acceleration, velocity, and position -- this is a physics application).

The way they work is that I've defined superclass methods thusly:

``` Mathematica
ancestor@v[t_] := $self@v0 + Integrate[$self@a[tt], {tt, 0, t}, Assumptions -> t \[Element] Reals];
ancestor@r[t_] := $self@r0 + Integrate[$self@v[tt], {tt, 0, t}, Assumptions -> t \[Element] Reals];
```

I then use `Plot[$self@v[t]]` or `Plot[$self@r[t]]` in the superclass methods that generate the plots. This all works just fine, EXCEPT that it's hideously slow, especially for the plot of the second integral `r[t]`. I've wrestled with this before, when not using objects or subclassing or anything, and what I decided is that the `Integrate[...]` functions were being called many many times during plotting, for every single plot point (and perhaps the first integral was being called many times during each execution of the second integral). Well, of course! It is defined as set-delayed, after all.

That is really unnecessary, since the `a[t]` function does not change once defined, and the indefinite integral only needs to be calculated once. Before using your OOP package, I simply replaced SetDelayed with Set in my definitions of the `v[t]` and `a[t]` functions, and all speed problems disappeared.

Unfortunately, I can't figure out how to do the same thing within this OOP/inheritance context. If I replace SetDelayed with Set in the superclass definitions of `ancestor@v[t_]` and `ancestor@r[t_]`, I get nasty cross-contamination between different child objects; it looks like the rule is being executed once per argument, regardless of which `$self` is involved. Somehow, the rule needs to execute once for each child object, and it needs to execute once for a generic variable argument to create a new function that gets stored, rather than once per numerical argument value.

I have come up with a workaround for my particular case: putting the plotting functions inside a Module and setting (not delayed) a temporary function equal to that original superclass set-delayed that worked fine but was slow, like this:

``` Mathematica
ancestor@vGraph[tF_] := Module[{vFunc},
  vFunc[t_] = $self@v[t];
  Plot[vFunc[t], {t, 0, tF},]]
```

That's not ideal, since in principle the integrated functions `v[t]` and `r[t]` should only be calculated once per child object (assuming the child's `a[t]` doesn't change once set), rather than once per call to the graphing method. It does, however, make my code work adequately.

I'm wondering whether you had any thoughts on this, because they might go a long way towards improving my understanding of your OOP system and how to navigate per-child vs. once-per-superclass issues.

(BTW, if you'd like me to re-post this as a question on Stack Exchange, please say so. I put it here because it seems very specific to your answer to a prior question, and to this package, and I don't yet have the reputation to post a comment.)

Thanks,
:Ian

**Comment by jkuczm** [comment]
You could add special caching method to your object:

``` Mathematica
ancestor@cacheVAndR[] :=
    Block[{t},
        $self@v[t_] = ancestor[v[t], $self];
        $self@r[t_] = ancestor[r[t], $self];
    ]
```

Now let's define a child:

``` Mathematica
ClearAll[child]
DeclareObject[child, ancestor]
```

After changing members relevant to `v[t]` and `r[t]` you can cache their values:

``` Mathematica
child@a[t_] := t^2
child@v0 = 5;
child@r0 = 10;
child@cacheVAndR[]
```

After caching, evaluated `v[t]` and `r[t]` are saved as members of `child` object:

``` Mathematica
?? child
(*...
child[v[t_],_:child]=5+t^3/3
child[r[t_],_:child]=10+5 t+t^4/12
...*)
```

It might be useful to re-cache `v[t]` and `r[t]` each time `r0`, `v0` or `a[t_]` changes.
This would be more complicated, but I can think about it, if you need it.

**Comment by ibeatty** [comment]
Sweet. I'll have to think about why that works and what `Block[...]` is doing here.

Thanks again!

**Comment by ibeatty** [comment]
How might I make `v[t]` and `r[t]` Listable? Can I use the same `addAttributes[...]` function as you suggested earlier? I thought about using that in the caching function, but that was for pure functions, and the caching function doesn't use pure functions.

**Comment by jkuczm** [comment]
`Block` in `cacheVAndR` is a safeguard. Right hand sides of assignments inside this method are evaluated. It could happen that when  `cacheVAndR` is called, `t` symbol has a value assigned, if so, without `Block`, this value would replace `t` symbol in definition of `v` and `r`.

This is not related to `ClasslessObjects`, it's a standard technique. See for example: [Scoping in assigning a derivative](http://mathematica.stackexchange.com/q/6664/14303).

As to `Listable` attribute:

``` Mathematica
ancestor@cacheVAndR[] :=
 With[
  {
   evaluatedV = ancestor[v[#], $self],
   evaluatedR = ancestor[r[#], $self]
   },
  $self@v[t_] := Function[Null, evaluatedV, Listable][t];
  $self@r[t_] := Function[Null, evaluatedR, Listable][t];
  ]
```

**Comment by jkuczm** [comment]
After rethinking this, solutions with auxiliary pure function are a bit hacky.
Explicit definition for `List` arguments should be cleaner:

``` Mathematica
ancestor@v[l_List] := $self@v[#] & /@ l
ancestor@r[l_List] := $self@r[#] & /@ l
ancestor@cacheVAndR[] :=
    Block[{t},
        $self@v[t : Except[_List]] = ancestor[v[t], $self];
        $self@r[t : Except[_List]] = ancestor[r[t], $self];
    ]
```

**Comment by ibeatty** [comment]
And… it works. Thanks again!
